defaults: &defaults
  help_page_url: https://www.railstutorial.org/help
  book_url: https://www.railstutorial.org/book
  help_page_text: "See the Ruby help page"
  book_link_text: "Ruby on Rails Tutorial book"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
